spring.application.name=HM

spring.datasource.url=jdbc:postgresql://localhost:5432/<YOUR DB>
spring.datasource.username=<USERNAME>
spring.datasource.password=<PASSWORD>
spring.jpa.hibernate.ddl-auto=update

logging.level.com.HostelManagement.HM.service=trace


media.twilio.auth-token=<TWILIO AUTH TOKEN>
media.twilio.account-sid=<TWILIO SID>

jwt.secret=<JWT SECRET>