spring.application.name=HM

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

#logging.level.com.HostelManagement.HM.service=trace

media.twilio.auth-token=${TWILIO_AUTH_TOKEN}
media.twilio.account-sid=${TWILIO_ACCOUNT_SID}

jwt.secret=${JWT_SECRET}